// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyuoxmavabpjqaxmpdaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5dW94bWF2YWJwanFheG1wZGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NzI0NzUsImV4cCI6MjA1NzA0ODQ3NX0.A5AUdeyW4hGSMUTWlGE2cME12_Zag8gYjPvTdNgyK-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);